sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
services: mongodb
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install "pycparser<2.19" coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=cameria setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: eBXdH8+/GDXZ9mIIODIHHzTGUu0HFwNAfTd/o4wpR9xMtOH72fEP2N8tY1CkTxf3+fnlSRx5JwP7qXP8fwE6Y4qrSmtE2SJJlUIJFGUnmKQc1vM0v6JsJJkXFGAWtKZPPSCaNWgDAabIZF+uIVwTv16XqqaZcVoLjVe7DYMzT2BU//5bLtdifnTQeLxDKFuFM/tHdDekaUD8bszE7agMbN9bz1zNoexpXjABkghMFoIxOP4LOf89wtuhBQfrJSQRr+gDyhvsHlNA91wt6glKc5CW4RlH8IrFXHVTYVGFNt/Cz8sRG/pwc1/FFUN4Nx1HeSOLcjJo82ytBt4FREpckEVzLgnguHPMHX3PWiUytrCnBwO4G8ng9xUZPg0/aLEidv1iV3Gg8CvYscGJjeO4NqRjZXDIkuj80L2IPPJf7spRwyXwUMXbE+gfsNzsZ4BQnW7BfRHDMj4uy9y60CulswXH1Uhd91ECWsHsinJ8EVGrFHNG7p1fDzuAg738x2PCcPYKcjq1VLqIWGtlnwEB2KFzyUYiIX62QQCiH13p0qm/hZys55o4d1G8U11Py920NSyz58ZnOZD0hiMmHFONOSGak8HibmmZPeoOiJiaU6nRzV9AOmz26gqSt7GFQcxCwM+o2xvJIYgdIWUlLOtDxVYJBAFVXCgOutYrsrCjlYY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
