sudo: false
dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=cameria setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: eBXdH8+/GDXZ9mIIODIHHzTGUu0HFwNAfTd/o4wpR9xMtOH72fEP2N8tY1CkTxf3+fnlSRx5JwP7qXP8fwE6Y4qrSmtE2SJJlUIJFGUnmKQc1vM0v6JsJJkXFGAWtKZPPSCaNWgDAabIZF+uIVwTv16XqqaZcVoLjVe7DYMzT2BU//5bLtdifnTQeLxDKFuFM/tHdDekaUD8bszE7agMbN9bz1zNoexpXjABkghMFoIxOP4LOf89wtuhBQfrJSQRr+gDyhvsHlNA91wt6glKc5CW4RlH8IrFXHVTYVGFNt/Cz8sRG/pwc1/FFUN4Nx1HeSOLcjJo82ytBt4FREpckEVzLgnguHPMHX3PWiUytrCnBwO4G8ng9xUZPg0/aLEidv1iV3Gg8CvYscGJjeO4NqRjZXDIkuj80L2IPPJf7spRwyXwUMXbE+gfsNzsZ4BQnW7BfRHDMj4uy9y60CulswXH1Uhd91ECWsHsinJ8EVGrFHNG7p1fDzuAg738x2PCcPYKcjq1VLqIWGtlnwEB2KFzyUYiIX62QQCiH13p0qm/hZys55o4d1G8U11Py920NSyz58ZnOZD0hiMmHFONOSGak8HibmmZPeoOiJiaU6nRzV9AOmz26gqSt7GFQcxCwM+o2xvJIYgdIWUlLOtDxVYJBAFVXCgOutYrsrCjlYY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
